In [201]:
from IPython.core.display import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings('ignore')

In [202]:
df=pd.read_csv('/content/ecommerce_user_behavior_8000.csv')

In [203]:
df

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [204]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [205]:
df.isnull().sum()

user_id               160
age                   160
gender                160
device_type           160
time_on_site          160
pages_viewed          160
previous_purchases    160
cart_items            160
discount_seen         160
ad_clicked            160
returning_user        160
avg_session_time      160
bounce_rate           160
purchase              160
dtype: int64

In [206]:
df.dropna(how='all')

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [207]:
np.sort(df['age'].unique())

array([18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
       57., 58., 59., nan])

In [208]:
df['age'].fillna(43,inplace=True)

In [209]:
df['age'].mode()

0    43.0
Name: age, dtype: float64

In [210]:

df.age.isnull().sum()

np.int64(0)

In [211]:
df['gender'].unique()

array(['Female', 'Male', nan], dtype=object)

In [212]:
df['gender'].isnull().sum()

np.int64(160)

In [213]:
df['gender'].value_counts()

gender
Male      3931
Female    3909
Name: count, dtype: int64

In [214]:
df['gender'].fillna(method='ffill',inplace=True)

In [215]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [216]:
df['device_type'].value_counts()

device_type
Mobile     4685
Desktop    2365
Tablet      790
Name: count, dtype: int64

In [217]:
df['device_type'].isna().sum()

np.int64(160)

In [218]:
df['device_type'].fillna('Mobile',inplace=True)

In [219]:
df.describe()

,user_id,age,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
count,7840.000000,8000.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000
mean,4003.135077,38.683875,15.714673,9.970026,6.964158,4.530230,0.502551,0.502296,0.509439,15.794999,49.924402,0.998342
std,2307.898984,11.928914,8.362764,5.425485,4.281117,2.865814,0.500025,0.500027,0.499943,9.864556,29.137449,0.040689
min,1.000000,18.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.570000,0.010000,0.000000
25%,2011.750000,29.000000,8.520000,5.000000,3.000000,2.000000,0.000000,0.000000,0.000000,7.750000,24.677500,1.000000
50%,3998.000000,39.000000,15.740000,10.000000,7.000000,5.000000,1.000000,1.000000,1.000000,14.300000,49.500000,1.000000
75%,6001.250000,49.000000,22.880000,15.000000,11.000000,7.000000,1.000000,1.000000,1.000000,22.392500,75.990000,1.000000
max,8000.000000,59.000000,30.000000,19.000000,14.000000,9.000000,1.000000,1.000000,1.000000,44.750000,99.970000,1.000000

In [220]:
df['returning_user'].value_counts()

returning_user
1.0    3994
0.0    3846
Name: count, dtype: int64

In [221]:
df

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,Mobile,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [222]:
def handle_null(df):
        i=4
        df.iloc[:,i].fillna(df.iloc[:,i].mean(),inplace=True)#timeonsite
        df.iloc[:,i+1].fillna(df.iloc[:,i+1].mean(),inplace=True)#pageviewed
        df.iloc[:,i+2].fillna(df.iloc[:,i+2].mean(),inplace=True)#previous_purchased
        df.iloc[:,i+3].fillna(df.iloc[:,i+3].mean(),inplace=True)#cart_item
        df.iloc[:,i+4].fillna(method='ffill',inplace=True)#discountseen
        df.iloc[:,i+5].fillna(method='ffill',inplace=True)#ad_clicked
        df.iloc[:,i+6].fillna(method='ffill',inplace=True)#returnuser
        df.iloc[:,i+7].fillna(df.iloc[:,i+6].mean(),inplace=True)#avg sessiontime
        df.iloc[:,i+8].fillna(df.iloc[:,i+7].mean(),inplace=True)#bouncerate
        df.iloc[:,i+9].fillna(method='ffill',inplace=True)#purchase

handle_null(df)

In [223]:
df.isnull().sum()

user_id               160
age                     0
gender                  0
device_type             0
time_on_site            0
pages_viewed            0
previous_purchases      0
cart_items              0
discount_seen           0
ad_clicked              1
returning_user          0
avg_session_time        0
bounce_rate             0
purchase                0
dtype: int64

In [224]:
df.ad_clicked.fillna(method='bfill',inplace=True)#ad_clicked

In [225]:
df=df.drop('user_id',axis=1)

In [226]:
df

,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,1.0,0.0,6.97000,28.18,1.0
1,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17000,86.73,1.0
2,32.0,Female,Mobile,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87000,83.09,1.0
3,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,0.50975,79.03,1.0
4,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15000,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01000,82.44,1.0
7996,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48000,10.06,1.0
7997,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57000,21.34,1.0
7998,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78000,2.03,1.0
7999,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28000,15.67,1.0

In [227]:
df.duplicated().sum()

np.int64(0)

In [228]:
from sklearn.preprocessing import OneHotEncoder

oe=OneHotEncoder(drop='first', sparse_output=False)
oe.fit(df[['gender']])
encoder=oe.transform(df[['gender']])
cols=oe.get_feature_names_out(['gender'])
df['gender_e']=pd.DataFrame(encoder,columns=cols)
df.drop('gender',axis=1,inplace=True)

In [229]:
from sklearn.preprocessing import OneHotEncoder
oe1=OneHotEncoder(drop='first', sparse_output=False)
oe1.fit(df[['device_type']])
encoder=oe1.transform(df[['device_type']])
cols=oe1.get_feature_names_out(['device_type'])
df[['device_deskt','device_tabl']]=encoder

In [230]:
df

,age,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase,gender_e,device_deskt,device_tabl
0,56.0,Desktop,12.90,8.0,13.0,1.0,1.0,1.0,0.0,6.97000,28.18,1.0,0.0,0.0,0.0
1,46.0,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17000,86.73,1.0,1.0,1.0,0.0
2,32.0,Mobile,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87000,83.09,1.0,0.0,1.0,0.0
3,25.0,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,0.50975,79.03,1.0,0.0,1.0,0.0
4,38.0,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15000,55.35,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,48.0,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01000,82.44,1.0,0.0,0.0,1.0
7996,54.0,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48000,10.06,1.0,1.0,1.0,0.0
7997,54.0,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57000,21.34,1.0,0.0,0.0,0.0
7998,32.0,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78000,2.03,1.0,0.0,1.0,0.0
7999,46.0,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28000,15.67,1.0,0.0,1.0,0.0

In [231]:
y=df['purchase']
X=df.drop(['purchase','device_type'],axis=1)

In [232]:
X

,age,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,gender_e,device_deskt,device_tabl
0,56.0,12.90,8.0,13.0,1.0,1.0,1.0,0.0,6.97000,28.18,0.0,0.0,0.0
1,46.0,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17000,86.73,1.0,1.0,0.0
2,32.0,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87000,83.09,0.0,1.0,0.0
3,25.0,22.71,5.0,10.0,1.0,0.0,0.0,1.0,0.50975,79.03,0.0,1.0,0.0
4,38.0,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15000,55.35,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,48.0,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01000,82.44,0.0,0.0,1.0
7996,54.0,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48000,10.06,1.0,1.0,0.0
7997,54.0,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57000,21.34,0.0,0.0,0.0
7998,32.0,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78000,2.03,0.0,1.0,0.0
7999,46.0,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28000,15.67,0.0,1.0,0.0

In [233]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [234]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [235]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,precision_score,recall_score
from sklearn.model_selection import GridSearchCV

In [236]:
models = {
    "Logistic": LogisticRegression(),
    "DecisionTree": DecisionTreeClassifier(),
    "RandomForest": RandomForestClassifier(),
    "SVC": SVC(),
    "KNN": KNeighborsClassifier(),
    "GaussianNB": GaussianNB(),
    "MultinomialNB": MultinomialNB(),
    "BernoulliNB": BernoulliNB()
}

for name, model in models.items():
    # Initialize with original data, then scale if needed
    X_train_model = X_train
    X_test_model = X_test

    if name in ["Logistic", "SVC", "KNN"]:
        # These models need scaled data using StandardScaler
        scaler = StandardScaler()
        X_train_model = scaler.fit_transform(X_train)
        X_test_model = scaler.transform(X_test)
    elif name in ["MultinomialNB", "BernoulliNB"]:
        # These need non-negative data using MinMaxScaler
        scaler = MinMaxScaler()
        X_train_model = scaler.fit_transform(X_train)
        X_test_model = scaler.transform(X_test)
    # Tree-based models or GaussianNB can use raw data by default

    # Fit the model
    model.fit(X_train_model, y_train)

    # Evaluate
    score_train = model.score(X_train_model, y_train)
    score_test = model.score(X_test_model, y_test)
    y_pred = model.predict(X_test_model) # Get predictions
    print(f"{name} Train Accuracy: {score_train:.4f}")

    print(f"{name} Test Accuracy: {score_test:.4f}")
    print(f"{name} accuracy score: {accuracy_score(y_test,y_pred):.4f}") # Use y_pred here

Logistic Train Accuracy: 0.9986
Logistic Test Accuracy: 0.9994
Logistic accuracy score: 0.9994
DecisionTree Train Accuracy: 1.0000
DecisionTree Test Accuracy: 0.9969
DecisionTree accuracy score: 0.9969
RandomForest Train Accuracy: 1.0000
RandomForest Test Accuracy: 0.9994
RandomForest accuracy score: 0.9994
SVC Train Accuracy: 0.9980
SVC Test Accuracy: 0.9994
SVC accuracy score: 0.9994
KNN Train Accuracy: 0.9980
KNN Test Accuracy: 0.9994
KNN accuracy score: 0.9994
GaussianNB Train Accuracy: 0.9983
GaussianNB Test Accuracy: 0.9969
GaussianNB accuracy score: 0.9969
MultinomialNB Train Accuracy: 0.9980
MultinomialNB Test Accuracy: 0.9994
MultinomialNB accuracy score: 0.9994
BernoulliNB Train Accuracy: 0.9980
BernoulliNB Test Accuracy: 0.9994
BernoulliNB accuracy score: 0.9994

In [237]:
#randomforest
y.value_counts()

purchase
1.0    7986
0.0      14
Name: count, dtype: int64

In [238]:
#imbalance data
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline # Import Pipeline from imblearn

# =========================
# Models
# =========================
models = {
    "Logistic": LogisticRegression(class_weight='balanced', max_iter=1000),
    "DecisionTree": DecisionTreeClassifier(class_weight='balanced'),
    "RandomForest": RandomForestClassifier(class_weight='balanced'),
    "SVC": SVC(class_weight='balanced', probability=True),
    "KNN": KNeighborsClassifier(),
    "GaussianNB": GaussianNB(),
    "MultinomialNB": MultinomialNB(),
    "BernoulliNB": BernoulliNB()
}

# =========================
# Loop through models
# =========================
results = {}

for name, model in models.items():

    print(f"\n========== {name} ==========")

    #  Decide pipeline based on model
    if name in ["Logistic", "SVC", "KNN"]:
        pipe = Pipeline([
            ('smote', SMOTE(random_state=42)),
            ('scaler', StandardScaler()),
            ('model', model)
        ])

    elif name in ["MultinomialNB"]:
        # No scaling for MultinomialNB
        pipe = Pipeline([
            ('smote', SMOTE(random_state=42)),
            ('model', model)
        ])

    else:
        # Tree + GaussianNB + BernoulliNB
        pipe = Pipeline([
            ('smote', SMOTE(random_state=42)),
            ('model', model)
        ])

    # =========================
    # Train
    # =========================
    pipe.fit(X_train, y_train)

    # =========================
    # Predict
    # =========================
    y_pred = pipe.predict(X_test)

    # =========================
    # Scores
    # =========================
    f1 = f1_score(y_test, y_pred)
    results[name] = f1

    print("F1 Score:", f1)
    print(classification_report(y_test, y_pred))

# =========================
# Final Comparison
# =========================
print("\n\nFinal Model Scores:")
for k, v in results.items():
    print(f"{k}: {v}")

========== Logistic ==========
F1 Score: 0.9908488482171032
              precision    recall  f1-score   support

         0.0       0.03      1.00      0.06         1
         1.0       1.00      0.98      0.99      1599

    accuracy                           0.98      1600
   macro avg       0.52      0.99      0.53      1600
weighted avg       1.00      0.98      0.99      1600


========== DecisionTree ==========
F1 Score: 0.9984350547730829
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== RandomForest ==========
F1 Score: 0.9996874023132228
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== SVC ==========
F1 Score: 0.9990616202690021
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== KNN ==========
F1 Score: 0.9968632371392723
              precision    recall  f1-score   support

         0.0       0.09      1.00      0.17         1
         1.0       1.00      0.99      1.00      1599

    accuracy                           0.99      1600
   macro avg       0.55      1.00      0.58      1600
weighted avg       1.00      0.99      1.00      1600


========== GaussianNB ==========
F1 Score: 0.9959183673469387
              precision    recall  f1-score   support

         0.0       0.07      1.00      0.13         1
         1.0       1.00      0.99      1.00      1599

    accuracy                           0.99      1600
   macro avg       0.54      1.00      0.56      1600
weighted avg       1.00      0.99      1.00      1600


========== MultinomialNB ==========
F1 Score: 0.9435084241823588
              precision    recall  f1-score   support

         0.0       0.01      1.00      0.01         1
         1.0       1.00      0.89      0.94      1599

    accuracy                           0.89      1600
   macro avg       0.50      0.95      0.48      1600
weighted avg       1.00      0.89      0.94      1600


========== BernoulliNB ==========
F1 Score: 0.7849544072948328
              precision    recall  f1-score   support

         0.0       0.00      1.00      0.00         1
         1.0       1.00      0.65      0.78      1599

    accuracy                           0.65      1600
   macro avg       0.50      0.82      0.39      1600
weighted avg       1.00      0.65      0.78      1600



Final Model Scores:
Logistic: 0.9908488482171032
DecisionTree: 0.9984350547730829
RandomForest: 0.9996874023132228
SVC: 0.9990616202690021
KNN: 0.9968632371392723
GaussianNB: 0.9959183673469387
MultinomialNB: 0.9435084241823588
BernoulliNB: 0.7849544072948328

In [239]:
from imblearn.pipeline import Pipeline # Import Pipeline from imblearn
best_models={}
models = {
    "Logistic": (
        LogisticRegression(class_weight='balanced', max_iter=1000),
        {
            'model__C': [0.1, 1, 10]
        }
    ),

    "DecisionTree": (
        DecisionTreeClassifier(class_weight='balanced'),
        {
            'model__max_depth': [5, 10, 20],
            'model__min_samples_split': [2, 5, 10]
        }
    ),

    "RandomForest": (
        RandomForestClassifier(class_weight='balanced'),
        {
            'model__n_estimators': [100, 200],
            'model__max_depth': [5, 10]
        }
    ),

    "SVC": (
        SVC(class_weight='balanced', probability=True),
        {
            'model__C': [0.1, 1, 10],
            'model__kernel': ['linear', 'rbf']
        }
    ),

    "KNN": (
        KNeighborsClassifier(),
        {
            'model__n_neighbors': [3, 5, 7]
        }
    ),

    "GaussianNB": (
        GaussianNB(),
        {}
    )
}

# =========================
# Loop with GridSearchCV
# =========================
results = {}

for name, (model, params) in models.items():

    print(f"\n========== {name} ==========")

    #  Pipeline selection
    if name in ["Logistic", "SVC", "KNN"]:
        pipe = Pipeline([
            ('smote', SMOTE(random_state=42)),
            ('scaler', StandardScaler()),
            ('model', model)
        ])
    else:
        pipe = Pipeline([
            ('smote', SMOTE(random_state=42)),
            ('model', model)
        ])

    # =========================
    # GridSearchCV
    # =========================
    grid = GridSearchCV(
        pipe,
        param_grid=params,
        cv=5,
        scoring='f1',
        n_jobs=-1
    )

    grid.fit(X_train, y_train)

    # =========================
    # Best Model
    # =========================
    best_model = grid.best_estimator_
    best_models[name] = best_model

    print("Best Params:", grid.best_params_)
    print("Best model:", grid.best_estimator_)
    # =========================
    # Prediction
    # =========================
    y_pred = best_model.predict(X_test)

    f1 = f1_score(y_test, y_pred)
    results[name] = f1

    print("F1 Score:", f1)
    print(classification_report(y_test, y_pred))

# =========================
# Final Comparison
# =========================
print("\n\nFinal Model Scores:")
for k, v in results.items():
    print(f"{k}: {v}")

========== Logistic ==========
Best Params: {'model__C': 10}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)), ('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(C=10, class_weight='balanced',
                                    max_iter=1000))])
F1 Score: 0.9921210211156634
              precision    recall  f1-score   support

         0.0       0.04      1.00      0.07         1
         1.0       1.00      0.98      0.99      1599

    accuracy                           0.98      1600
   macro avg       0.52      0.99      0.53      1600
weighted avg       1.00      0.98      0.99      1600


========== DecisionTree ==========
Best Params: {'model__max_depth': 20, 'model__min_samples_split': 2}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)),
                ('model',
                 DecisionTreeClassifier(class_weight='balanced',
                                        max_depth=20))])
F1 Score: 0.9990616202690021
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== RandomForest ==========
Best Params: {'model__max_depth': 10, 'model__n_estimators': 100}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        max_depth=10))])
F1 Score: 0.9996874023132228
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== SVC ==========
Best Params: {'model__C': 10, 'model__kernel': 'rbf'}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)), ('scaler', StandardScaler()),
                ('model',
                 SVC(C=10, class_weight='balanced', probability=True))])
F1 Score: 0.9990616202690021
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       1.00      1.00      1.00      1600


========== KNN ==========
Best Params: {'model__n_neighbors': 3}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)), ('scaler', StandardScaler()),
                ('model', KNeighborsClassifier(n_neighbors=3))])
F1 Score: 0.9978063303039799
              precision    recall  f1-score   support

         0.0       0.12      1.00      0.22         1
         1.0       1.00      1.00      1.00      1599

    accuracy                           1.00      1600
   macro avg       0.56      1.00      0.61      1600
weighted avg       1.00      1.00      1.00      1600


========== GaussianNB ==========
Best Params: {}
Best model: Pipeline(steps=[('smote', SMOTE(random_state=42)), ('model', GaussianNB())])
F1 Score: 0.9959183673469387
              precision    recall  f1-score   support

         0.0       0.07      1.00      0.13         1
         1.0       1.00      0.99      1.00      1599

    accuracy                           0.99      1600
   macro avg       0.54      1.00      0.56      1600
weighted avg       1.00      0.99      1.00      1600



Final Model Scores:
Logistic: 0.9921210211156634
DecisionTree: 0.9990616202690021
RandomForest: 0.9996874023132228
SVC: 0.9990616202690021
KNN: 0.9978063303039799
GaussianNB: 0.9959183673469387

In [240]:
print(best_models.keys())

dict_keys(['Logistic', 'DecisionTree', 'RandomForest', 'SVC', 'KNN', 'GaussianNB'])

In [241]:
final_model = best_models["RandomForest"]
import joblib
joblib.dump(final_model, "model.pkl")

['model.pkl']

In [242]:
X.describe()

,age,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,gender_e,device_deskt,device_tabl
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,38.683875,15.714673,9.970026,6.964158,4.530230,0.502625,0.502250,0.509750,15.489294,49.235700,0.500625,0.605625,0.098750
std,11.928914,8.278703,5.370950,4.238085,2.837007,0.500024,0.500026,0.499936,9.997145,29.244711,0.500031,0.488747,0.298345
min,18.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.509750,0.010000,0.000000,0.000000,0.000000
25%,29.000000,8.690000,5.000000,3.000000,2.000000,0.000000,0.000000,0.000000,7.390000,23.087500,0.000000,0.000000,0.000000
50%,39.000000,15.714673,10.000000,7.000000,4.530230,1.000000,1.000000,1.000000,14.030000,48.275000,1.000000,1.000000,0.000000
75%,49.000000,22.740000,15.000000,11.000000,7.000000,1.000000,1.000000,1.000000,22.180000,75.412500,1.000000,1.000000,0.000000
max,59.000000,30.000000,19.000000,14.000000,9.000000,1.000000,1.000000,1.000000,44.750000,99.970000,1.000000,1.000000,1.000000

In [243]:
import streamlit as st
import joblib
import pandas as pd

# Load model
model = joblib.load("model.pkl")

st.title("🛒 Purchase Prediction App")

# Inputs
age = st.number_input("Age", 10, 60)
time_on_site = st.number_input("Time on Site", 0, 300)
pages_viewed = st.number_input("Pages Viewed", 1, 25)
previous_purchases = st.number_input("Previous Purchases", 0, 20)
cart_items = st.number_input("Cart Items", 0, 15)

discount_seen = st.selectbox("Discount Seen", [0, 1])
ad_clicked = st.selectbox("Ad Clicked", [0, 1])
returning_user = st.selectbox("Returning User", [0, 1])

avg_session_time = st.number_input("Avg Session Time", 0, 100)
bounce_rate = st.number_input("Bounce Rate", 0.0, 1.0)

gender_e = st.selectbox("Gender (Encoded)", [0, 1])
device_deskt = st.selectbox("Device Desktop", [0, 1])
device_tabl = st.selectbox("Device Tablet", [0, 1])

# DataFrame
input_data = pd.DataFrame({
    'age': [age],
    'time_on_site': [time_on_site],
    'pages_viewed': [pages_viewed],
    'previous_purchases': [previous_purchases],
    'cart_items': [cart_items],
    'discount_seen': [discount_seen],
    'ad_clicked': [ad_clicked],
    'returning_user': [returning_user],
    'avg_session_time': [avg_session_time],
    'bounce_rate': [bounce_rate],
    'gender_e': [gender_e],
    'device_deskt': [device_deskt],
    'device_tabl': [device_tabl]
})

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    st.subheader("Result:")

    if prediction == 1:
        st.success(f"User WILL Purchase (Confidence: {probability:.2f})")
    else:
        st.error(f"User will NOT Purchase (Confidence: {probability:.2f})")

2026-04-08 04:05:10.857 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.858 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.863 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.865 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.867 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.871 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.872 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.876 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.879 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.881 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.883 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.889 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.891 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.898 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.900 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.929 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.931 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.931 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.934 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.936 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.936 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.939 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.941 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.943 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.944 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.945 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.946 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.948 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.949 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.951 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.952 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.952 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.954 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.955 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.961 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-08 04:05:10.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.